export const TRANSLATIONS = {
  // =================================================================
  // 1. FRANÇAIS (Référence Complète)
  // =================================================================
  "Français": {
    email_subject: "Avis de crédit - Direction des Transferts",
    greeting: "Bonjour",
    intro_message: "La direction des ordres de transfert vous informe que {{debiteurNom}} a enregistré avec succès un ordre de virement en votre faveur. Les fonds ont été provisionnés et sont actuellement en cours de traitement conformément aux protocoles de sécurité bancaires et aux vérifications réglementaires en vigueur. Votre compte sera crédité selon les standards SEPA/SWIFT. Vous recevrez une confirmation dès la finalisation de l'opération.",
    
    footer_auto: "Message généré par",
    footer_contact: "Pour toute question, notre service client reste à votre disposition.",
    footer_security: "Direction des ordres de transfert",
    
    // --- NOUVEAUX LABELS DEMANDÉS ---
    label_beneficiary_name: "Bénéficiaire",
    label_execution_date: "Date d'exécution",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Adresse de la banque",
    label_country: "Pays",

    // Labels existants
    label_amount: "Montant provisionné",
    label_sender: "Émetteur",
    label_date: "Date d'enregistrement",
    label_motive: "Référence de transaction",
    label_bank: "Banque émettrice",
    label_key: "Clé RIB",
    
    // --- STATUTS VIREMENT ---
    status_pending: "En attente",
    status_processing: "En cours",
    status_completed: "Effectué",
    status_rejected: "Rejeté",

    // Bordereau PDF
    header_title: "BORDEREAU DE VIREMENT",
    subtitle: "Virement ordinaire",
    country_dest: "Pays de destination",
    amount_sum: "La somme de",
    currency_label: "Devise",
    amount_digits_desc: "Montant et devise en chiffre",
    debit_from: "Par le débit du compte",
    debit_account_desc: "Numéro de compte",
    name_desc: "Nom et prénom / Raison sociale",
    beneficiary: "Bénéficiaire",
    beneficiary_label: "Au bénéfice de",
    beneficiary_desc: "Nom du bénéficiaire",
    bank_info: "Information bancaire",
    beneficiary_sub: "(Bénéficiaire)",
    credit_account_desc: "Compte à créditer (IBAN)",
    bic_desc: "Code BIC / SWIFT",
    bank_name_label: "Banque",
    bank_name_desc: "Nom de la banque",
    bank_addr_label: "Adresse de la banque",
    signature: "Signature",
    
    // --- VALEURS DYNAMIQUES (Motifs) ---
    m_facture: "Facture", m_loyer: "Loyer", m_services: "Services", m_achat: "Achat", m_remboursement: "Remboursement", 
    m_salaire: "Salaire", m_donation: "Donation", m_dons: "Dons", m_aide_familiale: "Aide familiale", m_investissement: "Investissement", 
    m_voyage: "Voyage", m_pret_personnel: "Prêt personnel", m_frais_medicaux: "Frais médicaux", m_frais_etude: "Frais d’étude", 
    m_achat_vehicule: "Achat véhicule", m_frais_reparation: "Frais de réparation", m_cadeau: "Cadeau", m_cotisation: "Cotisation", 
    m_abonnement: "Abonnement", m_autre: "Autre", m_assurance: "Assurance", m_impots: "Impôts",
    
    // --- VALEURS DYNAMIQUES (Pays) ---
    c_france: "France", c_italie: "Italie", c_espagne: "Espagne", c_portugal: "Portugal", c_russie: "Russie",
    c_argentine: "Argentine", c_bresil: "Brésil", c_slovaquie: "Slovaquie", c_republique_tcheque: "République tchèque",
    c_pologne: "Pologne", c_allemagne: "Allemagne", c_suisse: "Suisse", c_roumanie: "Roumanie",
    c_ukraine: "Ukraine", c_croatie: "Croatie", c_slovenie: "Slovénie",
    c_royaume_uni: "Royaume-Uni", c_belgique: "Belgique", c_pays_bas: "Pays-Bas", c_autriche: "Autriche", c_suede: "Suède",
    c_etats_unis: "États-Unis", c_canada: "Canada", c_mexique: "Mexique", c_colombie: "Colombie", c_chili: "Chili", c_perou: "Pérou"
  },

  // =================================================================
  // 2. ANGLAIS
  // =================================================================
  "Anglais": {
    email_subject: "Credit Advice - Transfer Dept.",
    greeting: "Hello",
    // MODIFICATION ICI
    intro_message: "The Transfer Order Department informs you that {{debiteurNom}} has successfully registered a transfer order in your favor. Funds have been provisioned and are currently being processed in accordance with banking security protocols and regulatory checks. Your account will be credited according to SEPA/SWIFT standards. You will receive confirmation upon finalization.",
    
    footer_auto: "Message generated by",
    footer_contact: "For any questions, our customer service remains at your disposal.",
    footer_security: "Transfer Order Department",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Beneficiary",
    label_execution_date: "Execution Date",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Bank Address",
    label_country: "Country",

    label_amount: "Provisioned Amount",
    label_sender: "Issuer",
    label_date: "Registration Date",
    label_motive: "Transaction Reference",
    label_bank: "Issuing Bank",
    label_key: "Key",
    
    // --- STATUSES ---
    status_pending: "Pending",
    status_processing: "Processing",
    status_completed: "Completed",
    status_rejected: "Rejected",

    header_title: "TRANSFER SLIP",
    subtitle: "Standard Transfer",
    country_dest: "Destination Country",
    amount_sum: "The sum of",
    currency_label: "Currency",
    amount_digits_desc: "Amount and currency in digits",
    debit_from: "By debiting account",
    debit_account_desc: "Account Number",
    name_desc: "Full Name / Company Name",
    beneficiary: "Beneficiary",
    beneficiary_label: "For the benefit of",
    beneficiary_desc: "Beneficiary Name",
    bank_info: "Banking Information",
    beneficiary_sub: "(Beneficiary)",
    credit_account_desc: "Account to credit (IBAN)",
    bic_desc: "BIC / SWIFT Code",
    bank_name_label: "Bank",
    bank_name_desc: "Bank Name",
    bank_addr_label: "Bank Address",
    signature: "Signature",

    // --- DYNAMIC VALUES ---
    m_facture: "Invoice", m_loyer: "Rent", m_services: "Services", m_achat: "Purchase", m_remboursement: "Refund", 
    m_salaire: "Salary", m_donation: "Donation", m_dons: "Donations", m_aide_familiale: "Family Support", m_investissement: "Investment", 
    m_voyage: "Travel", m_pret_personnel: "Personal Loan", m_frais_medicaux: "Medical Expenses", m_frais_etude: "Tuition Fees", 
    m_achat_vehicule: "Vehicle Purchase", m_frais_reparation: "Repair Costs", m_cadeau: "Gift", m_cotisation: "Membership Fee", 
    m_abonnement: "Subscription", m_autre: "Other", m_assurance: "Insurance", m_impots: "Taxes",
    
    c_france: "France", c_italie: "Italy", c_espagne: "Spain", c_portugal: "Portugal", c_russie: "Russia",
    c_argentine: "Argentina", c_bresil: "Brazil", c_slovaquie: "Slovakia", c_republique_tcheque: "Czech Republic",
    c_pologne: "Poland", c_allemagne: "Germany", c_suisse: "Switzerland", c_roumanie: "Romania",
    c_ukraine: "Ukraine", c_croatie: "Croatia", c_slovenie: "Slovenia",
    c_royaume_uni: "United Kingdom", c_belgique: "Belgium", c_pays_bas: "Netherlands", c_autriche: "Austria", c_suede: "Sweden",
    c_etats_unis: "United States", c_canada: "Canada", c_mexique: "Mexico", c_colombie: "Colombia", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 3. ALLEMAND
  // =================================================================
  "Allemand": {
    email_subject: "Gutschriftsanzeige - Transferabteilung",
    greeting: "Guten Tag",
    // MODIFICATION ICI
    intro_message: "Die Abteilung für Überweisungsaufträge teilt Ihnen mit, dass {{debiteurNom}} erfolgreich einen Überweisungsauftrag zu Ihren Gunsten registriert hat. Die Gelder wurden bereitgestellt und werden derzeit gemäß den banküblichen Sicherheitsprotokollen und geltenden Vorschriften bearbeitet. Ihr Konto wird gemäß SEPA/SWIFT-Standards gutgeschrieben.",
    
    footer_auto: "Nachricht generiert von",
    footer_contact: "Bei Fragen steht Ihnen unser Kundendienst zur Verfügung.",
    footer_security: "Abteilung für Überweisungsaufträge",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Begünstigter",
    label_execution_date: "Ausführungsdatum",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Bankadresse",
    label_country: "Land",

    label_amount: "Bereitgestellter Betrag",
    label_sender: "Absender",
    label_date: "Registrierungsdatum",
    label_motive: "Transaktionsreferenz",
    label_bank: "Senderbank",
    label_key: "Prüfziffer",
    
    // --- STATUSES ---
    status_pending: "Ausstehend",
    status_processing: "In Bearbeitung",
    status_completed: "Erledigt",
    status_rejected: "Abgelehnt",

    header_title: "ÜBERWEISUNGSBELEG",
    subtitle: "Standardüberweisung",
    country_dest: "Zielland",
    amount_sum: "Die Summe von",
    currency_label: "Währung",
    amount_digits_desc: "Betrag und Währung in Ziffern",
    debit_from: "Durch Belastung von Konto",
    debit_account_desc: "Kontonummer",
    name_desc: "Vollständiger Name / Firmenname",
    beneficiary: "Begünstigter",
    beneficiary_label: "Zugunsten von",
    beneficiary_desc: "Name des Begünstigten",
    bank_info: "Bankverbindung",
    beneficiary_sub: "(Begünstigter)",
    credit_account_desc: "Gutschriftskonto (IBAN)",
    bic_desc: "BIC / SWIFT-Code",
    bank_name_label: "Bank",
    bank_name_desc: "Name der Bank",
    bank_addr_label: "Bankadresse",
    signature: "Unterschrift",

    // --- DYNAMIC VALUES ---
    m_facture: "Rechnung", m_loyer: "Miete", m_services: "Dienstleistungen", m_achat: "Kauf", m_remboursement: "Rückerstattung", 
    m_salaire: "Gehalt", m_donation: "Schenkung", m_dons: "Spenden", m_aide_familiale: "Familienhilfe", m_investissement: "Investition", 
    m_voyage: "Reise", m_pret_personnel: "Privatkredit", m_frais_medicaux: "Medizinische Kosten", m_frais_etude: "Studiengebühren", 
    m_achat_vehicule: "Fahrzeugkauf", m_frais_reparation: "Reparaturkosten", m_cadeau: "Geschenk", m_cotisation: "Beitrag", 
    m_abonnement: "Abonnement", m_autre: "Andere", m_assurance: "Versicherung", m_impots: "Steuern",

    c_france: "Frankreich", c_italie: "Italien", c_espagne: "Spanien", c_portugal: "Portugal", c_russie: "Russland",
    c_argentine: "Argentinien", c_bresil: "Brasilien", c_slovaquie: "Slowakei", c_republique_tcheque: "Tschechien",
    c_pologne: "Polen", c_allemagne: "Deutschland", c_suisse: "Schweiz", c_roumanie: "Rumänien",
    c_ukraine: "Ukraine", c_croatie: "Kroatien", c_slovenie: "Slowenien",
    c_royaume_uni: "Vereinigtes Königreich", c_belgique: "Belgien", c_pays_bas: "Niederlande", c_autriche: "Österreich", c_suede: "Schweden",
    c_etats_unis: "Vereinigte Staaten", c_canada: "Kanada", c_mexique: "Mexiko", c_colombie: "Kolumbien", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 4. ESPAGNOL
  // =================================================================
  "Espagnol": {
    email_subject: "Aviso de crédito - Dpto. Transferencias",
    greeting: "Hola",
    // MODIFICATION ICI
    intro_message: "La Dirección de Órdenes de Transferencia le informa que {{debiteurNom}} ha registrado con éxito una orden de transferencia a su favor. Los fondos han sido provisionados y están siendo procesados conforme a los protocolos de seguridad bancaria y verificaciones reglamentarias vigentes. Su cuenta será acreditada según los estándares SEPA/SWIFT.",
    
    footer_auto: "Mensaje generado por",
    footer_contact: "Para cualquier consulta, nuestro servicio de atención al cliente está a su disposición.",
    footer_security: "Dirección de Órdenes",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Beneficiario",
    label_execution_date: "Fecha de ejecución",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Dirección del banco",
    label_country: "País",

    label_amount: "Importe provisionado",
    label_sender: "Emisor",
    label_date: "Fecha de registro",
    label_motive: "Referencia de transacción",
    label_bank: "Banco emisor",
    label_key: "Clave",
    
    // --- STATUSES ---
    status_pending: "Pendiente",
    status_processing: "En proceso",
    status_completed: "Completado",
    status_rejected: "Rechazado",

    header_title: "COMPROBANTE DE TRANSFERENCIA",
    subtitle: "Transferencia estándar",
    country_dest: "País de destino",
    amount_sum: "La suma de",
    currency_label: "Divisa",
    amount_digits_desc: "Importe y divisa en cifras",
    debit_from: "Por débito de la cuenta",
    debit_account_desc: "Número de cuenta",
    name_desc: "Nombre completo / Razón social",
    beneficiary: "Beneficiario",
    beneficiary_label: "En beneficio de",
    beneficiary_desc: "Nombre del beneficiario",
    bank_info: "Datos bancarios",
    beneficiary_sub: "(Beneficiario)",
    credit_account_desc: "Cuenta a abonar (IBAN)",
    bic_desc: "Código BIC / SWIFT",
    bank_name_label: "Banco",
    bank_name_desc: "Nombre del banco",
    bank_addr_label: "Dirección del banco",
    signature: "Firma",

    // --- DYNAMIC VALUES ---
    m_facture: "Factura", m_loyer: "Alquiler", m_services: "Servicios", m_achat: "Compra", m_remboursement: "Reembolso", 
    m_salaire: "Salario", m_donation: "Donación", m_dons: "Donaciones", m_aide_familiale: "Ayuda familiar", m_investissement: "Inversión", 
    m_voyage: "Viaje", m_pret_personnel: "Préstamo personal", m_frais_medicaux: "Gastos médicos", m_frais_etude: "Gastos de estudio", 
    m_achat_vehicule: "Compra de vehículo", m_frais_reparation: "Gastos de reparación", m_cadeau: "Regalo", m_cotisation: "Cuota", 
    m_abonnement: "Suscripción", m_autre: "Otro", m_assurance: "Seguro", m_impots: "Impuestos",

    c_france: "Francia", c_italie: "Italia", c_espagne: "España", c_portugal: "Portugal", c_russie: "Rusia",
    c_argentine: "Argentina", c_bresil: "Brasil", c_slovaquie: "Eslovaquia", c_republique_tcheque: "República Checa",
    c_pologne: "Polonia", c_allemagne: "Alemania", c_suisse: "Suiza", c_roumanie: "Rumania",
    c_ukraine: "Ucrania", c_croatie: "Croacia", c_slovenie: "Eslovenia",
    c_royaume_uni: "Reino Unido", c_belgique: "Bélgica", c_pays_bas: "Países Bajos", c_autriche: "Austria", c_suede: "Suecia",
    c_etats_unis: "Estados Unidos", c_canada: "Canadá", c_mexique: "México", c_colombie: "Colombia", c_chili: "Chile", c_perou: "Perú"
  },

  // =================================================================
  // 5. ITALIEN
  // =================================================================
  "Italien": {
    email_subject: "Avviso di accredito - Direzione Trasferimenti",
    greeting: "Buongiorno",
    // MODIFICATION ICI
    intro_message: "La Direzione degli Ordini di Trasferimento La informa che {{debiteurNom}} ha registrato con successo un ordine di bonifico a Suo favore. I fondi sono stati accantonati e sono attualmente in corso di elaborazione in conformità con i protocolli di sicurezza bancaria e le verifiche normative vigenti.",
    
    footer_auto: "Messaggio generato da",
    footer_contact: "Per qualsiasi domanda, il nostro servizio clienti rimane a vostra disposizione.",
    footer_security: "Direzione Ordini",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Beneficiario",
    label_execution_date: "Data di esecuzione",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Indirizzo della banca",
    label_country: "Paese",

    label_amount: "Importo accantonato",
    label_sender: "Emittente",
    label_date: "Data di registrazione",
    label_motive: "Riferimento transazione",
    label_bank: "Banca emittente",
    label_key: "Chiave",
    
    // --- STATUSES ---
    status_pending: "In attesa",
    status_processing: "In lavorazione",
    status_completed: "Completato",
    status_rejected: "Respinto",

    header_title: "DISTINTA DI BONIFICO",
    subtitle: "Bonifico ordinario",
    country_dest: "Paese di destinazione",
    amount_sum: "La somma di",
    currency_label: "Valuta",
    amount_digits_desc: "Importo e valuta in cifre",
    debit_from: "Addebito sul conto",
    debit_account_desc: "Numero di conto",
    name_desc: "Nome e cognome / Ragione sociale",
    beneficiary: "Beneficiario",
    beneficiary_label: "A favore di",
    beneficiary_desc: "Nome del beneficiario",
    bank_info: "Coordinate bancarie",
    beneficiary_sub: "(Beneficiario)",
    credit_account_desc: "Conto da accreditare (IBAN)",
    bic_desc: "Codice BIC / SWIFT",
    bank_name_label: "Banca",
    bank_name_desc: "Nome della banca",
    bank_addr_label: "Indirizzo della banca",
    signature: "Firma",

    // --- DYNAMIC VALUES ---
    m_facture: "Fattura", m_loyer: "Affitto", m_services: "Servizi", m_achat: "Acquisto", m_remboursement: "Rimborso", 
    m_salaire: "Stipendio", m_donation: "Donazione", m_dons: "Donazioni", m_aide_familiale: "Aiuto familiare", m_investissement: "Investimento", 
    m_voyage: "Viaggio", m_pret_personnel: "Prestito personale", m_frais_medicaux: "Spese mediche", m_frais_etude: "Spese scolastiche", 
    m_achat_vehicule: "Acquisto veicolo", m_frais_reparation: "Spese di riparazione", m_cadeau: "Regalo", m_cotisation: "Quota", 
    m_abonnement: "Abbonamento", m_autre: "Altro", m_assurance: "Assicurazione", m_impots: "Tasse",

    c_france: "Francia", c_italie: "Italia", c_espagne: "Spagna", c_portugal: "Portogallo", c_russie: "Russia",
    c_argentine: "Argentina", c_bresil: "Brasile", c_slovaquie: "Slovacchia", c_republique_tcheque: "Repubblica Ceca",
    c_pologne: "Polonia", c_allemagne: "Germania", c_suisse: "Svizzera", c_roumanie: "Romania",
    c_ukraine: "Ucraina", c_croatie: "Croazia", c_slovenie: "Slovenia",
    c_royaume_uni: "Regno Unito", c_belgique: "Belgio", c_pays_bas: "Paesi Bassi", c_autriche: "Austria", c_suede: "Svezia",
    c_etats_unis: "Stati Uniti", c_canada: "Canada", c_mexique: "Messico", c_colombie: "Colombia", c_chili: "Cile", c_perou: "Perù"
  },

  // =================================================================
  // 6. PORTUGAIS
  // =================================================================
  "Portugais": {
    email_subject: "Aviso de crédito - Direção de Transferências",
    greeting: "Olá",
    // MODIFICATION ICI
    intro_message: "A Direção de Ordens de Transferência informa que {{debiteurNom}} registou com sucesso uma ordem de transferência a seu favor. Os fundos foram provisionados e estão atualmente a ser processados de acordo com os protocolos de segurança bancária e verificações regulamentares em vigor.",
    
    footer_auto: "Mensagem gerada por",
    footer_contact: "Para qualquer questão, o nosso serviço de apoio ao cliente está à sua disposição.",
    footer_security: "Direção de Ordens",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Beneficiário",
    label_execution_date: "Data de execução",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Endereço do banco",
    label_country: "País",

    label_amount: "Valor provisionado",
    label_sender: "Emissor",
    label_date: "Data de registo",
    label_motive: "Referência da transação",
    label_bank: "Banco emissor",
    label_key: "Chave",
    
    // --- STATUSES ---
    status_pending: "Pendente",
    status_processing: "Em processamento",
    status_completed: "Concluído",
    status_rejected: "Rejeitado",

    header_title: "COMPROVATIVO DE TRANSFERÊNCIA",
    subtitle: "Transferência normal",
    country_dest: "País de destino",
    amount_sum: "A soma de",
    currency_label: "Moeda",
    amount_digits_desc: "Montante e moeda em algarismos",
    debit_from: "Por débito da conta",
    debit_account_desc: "Número da conta",
    name_desc: "Nome completo / Empresa",
    beneficiary: "Beneficiário",
    beneficiary_label: "A favor de",
    beneficiary_desc: "Nome do beneficiário",
    bank_info: "Dados bancários",
    beneficiary_sub: "(Beneficiário)",
    credit_account_desc: "Conta a creditar (IBAN)",
    bic_desc: "Código BIC / SWIFT",
    bank_name_label: "Banco",
    bank_name_desc: "Nome do banco",
    bank_addr_label: "Endereço do banco",
    signature: "Assinatura",

    // --- DYNAMIC VALUES ---
    m_facture: "Fatura", m_loyer: "Aluguel", m_services: "Serviços", m_achat: "Compra", m_remboursement: "Reembolso", 
    m_salaire: "Salário", m_donation: "Doação", m_dons: "Donativos", m_aide_familiale: "Ajuda familiar", m_investissement: "Investimento", 
    m_voyage: "Viagem", m_pret_personnel: "Empréstimo pessoal", m_frais_medicaux: "Despesas médicas", m_frais_etude: "Despesas escolares", 
    m_achat_vehicule: "Compra de veículo", m_frais_reparation: "Custos de reparação", m_cadeau: "Presente", m_cotisation: "Cota", 
    m_abonnement: "Assinatura", m_autre: "Outro", m_assurance: "Seguro", m_impots: "Impostos",

    c_france: "França", c_italie: "Itália", c_espagne: "Espanha", c_portugal: "Portugal", c_russie: "Rússia",
    c_argentine: "Argentina", c_bresil: "Brasil", c_slovaquie: "Eslováquia", c_republique_tcheque: "República Checa",
    c_pologne: "Polônia", c_allemagne: "Alemanha", c_suisse: "Suíça", c_roumanie: "Romênia",
    c_ukraine: "Ucrânia", c_croatie: "Croácia", c_slovenie: "Eslovênia",
    c_royaume_uni: "Reino Unido", c_belgique: "Bélgica", c_pays_bas: "Países Baixos", c_autriche: "Áustria", c_suede: "Suécia",
    c_etats_unis: "Estados Unidos", c_canada: "Canadá", c_mexique: "México", c_colombie: "Colômbia", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 7. NÉERLANDAIS
  // =================================================================
  "Néerlandais": {
    email_subject: "Creditnota - Transferafdeling",
    greeting: "Hallo",
    // MODIFICATION ICI
    intro_message: "De Directie Transferorders informeert u dat {{debiteurNom}} met succes een overschrijvingsopdracht in uw voordeel heeft geregistreerd. De fondsen zijn gereserveerd en worden momenteel verwerkt in overeenstemming met de geldende bankbeveiligingsprotocollen en regelgevende controles.",
    
    footer_auto: "Bericht gegenereerd door",
    footer_contact: "Voor vragen blijft onze klantenservice tot uw beschikking.",
    footer_security: "Directie Transferorders",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Begunstigde",
    label_execution_date: "Uitvoeringsdatum",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Bankadres",
    label_country: "Land",

    label_amount: "Gereserveerd bedrag",
    label_sender: "Afzender",
    label_date: "Registratiedatum",
    label_motive: "Transactiereferentie",
    label_bank: "Uitgevende bank",
    label_key: "Sleutel",
    
    // --- STATUSES ---
    status_pending: "In afwachting",
    status_processing: "In behandeling",
    status_completed: "Voltooid",
    status_rejected: "Geweigerd",

    header_title: "OVERSCHRIJVINGSBEWIJS",
    subtitle: "Standaard overschrijving",
    country_dest: "Land van bestemming",
    amount_sum: "De som van",
    currency_label: "Valuta",
    amount_digits_desc: "Bedrag en valuta in cijfers",
    debit_from: "Via debitering van rekening",
    debit_account_desc: "Rekeningnummer",
    name_desc: "Volledige naam / Bedrijfsnaam",
    beneficiary: "Begunstigde",
    beneficiary_label: "Ten gunste van",
    beneficiary_desc: "Naam begunstigde",
    bank_info: "Bankgegevens",
    beneficiary_sub: "(Begunstigde)",
    credit_account_desc: "Te crediteren rekening (IBAN)",
    bic_desc: "BIC / SWIFT-code",
    bank_name_label: "Bank",
    bank_name_desc: "Naam van de bank",
    bank_addr_label: "Bankadres",
    signature: "Handtekening",

    // --- DYNAMIC VALUES ---
    m_facture: "Factuur", m_loyer: "Huur", m_services: "Diensten", m_achat: "Aankoop", m_remboursement: "Terugbetaling", 
    m_salaire: "Salaris", m_donation: "Schenking", m_dons: "Donaties", m_aide_familiale: "Gezinshulp", m_investissement: "Investering", 
    m_voyage: "Reis", m_pret_personnel: "Persoonlijke lening", m_frais_medicaux: "Medische kosten", m_frais_etude: "Studiekosten", 
    m_achat_vehicule: "Aankoop voertuig", m_frais_reparation: "Reparatiekosten", m_cadeau: "Cadeau", m_cotisation: "Contributie", 
    m_abonnement: "Abonnement", m_autre: "Anders", m_assurance: "Verzekering", m_impots: "Belastingen",

    c_france: "Frankrijk", c_italie: "Italië", c_espagne: "Spanje", c_portugal: "Portugal", c_russie: "Rusland",
    c_argentine: "Argentinië", c_bresil: "Brazilië", c_slovaquie: "Slowakije", c_republique_tcheque: "Tsjechië",
    c_pologne: "Polen", c_allemagne: "Duitsland", c_suisse: "Zwitserland", c_roumanie: "Roemenië",
    c_ukraine: "Oekraïne", c_croatie: "Kroatië", c_slovenie: "Slovenië",
    c_royaume_uni: "Verenigd Koninkrijk", c_belgique: "België", c_pays_bas: "Nederland", c_autriche: "Oostenrijk", c_suede: "Zweden",
    c_etats_unis: "Verenigde Staten", c_canada: "Canada", c_mexique: "Mexico", c_colombie: "Colombia", c_chili: "Chili", c_perou: "Peru"
  },

  // =================================================================
  // 8. POLONAIS
  // =================================================================
  "Polonais": {
    email_subject: "Awizo kredytowe - Dział Przelewów",
    greeting: "Witaj",
    // MODIFICATION ICI
    intro_message: "Dyrekcja Zleceń Przelewów informuje, że {{debiteurNom}} pomyślnie zarejestrował zlecenie przelewu na Twoją korzyść. Środki zostały zabezpieczone i są obecnie przetwarzane zgodnie z obowiązującymi protokołami bezpieczeństwa bankowego i kontrolami regulacyjnymi.",
    
    footer_auto: "Wiadomość wygenerowana przez",
    footer_contact: "W razie pytań nasz dział obsługi klienta pozostaje do dyspozycji.",
    footer_security: "Dyrekcja Zleceń",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Beneficjent",
    label_execution_date: "Data wykonania",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Adres banku",
    label_country: "Kraj",

    label_amount: "Zabezpieczona kwota",
    label_sender: "Nadawca",
    label_date: "Data rejestracji",
    label_motive: "Numer referencyjny",
    label_bank: "Bank nadawcy",
    label_key: "Klucz",
    
    // --- STATUSES ---
    status_pending: "Oczekujący",
    status_processing: "W toku",
    status_completed: "Zakończony",
    status_rejected: "Odrzucony",

    header_title: "DOWÓD PRZELEWU",
    subtitle: "Przelew standardowy",
    country_dest: "Kraj docelowy",
    amount_sum: "Kwota",
    currency_label: "Waluta",
    amount_digits_desc: "Kwota i waluta cyframi",
    debit_from: "Obciążenie rachunku",
    debit_account_desc: "Numer rachunku",
    name_desc: "Imię i nazwisko / Nazwa firmy",
    beneficiary: "Beneficjent",
    beneficiary_label: "Na rzecz",
    beneficiary_desc: "Nazwa beneficjenta",
    bank_info: "Dane bankowe",
    beneficiary_sub: "(Beneficjent)",
    credit_account_desc: "Rachunek uznania (IBAN)",
    bic_desc: "Kod BIC / SWIFT",
    bank_name_label: "Bank",
    bank_name_desc: "Nazwa banku",
    bank_addr_label: "Adres banku",
    signature: "Podpis",

    // --- DYNAMIC VALUES ---
    m_facture: "Faktura", m_loyer: "Czynsz", m_services: "Usługi", m_achat: "Zakup", m_remboursement: "Zwrot", 
    m_salaire: "Wynagrodzenie", m_donation: "Darowizna", m_dons: "Datki", m_aide_familiale: "Pomoc rodzinna", m_investissement: "Inwestycja", 
    m_voyage: "Podróż", m_pret_personnel: "Pożyczka osobista", m_frais_medicaux: "Koszty leczenia", m_frais_etude: "Opłaty za studia", 
    m_achat_vehicule: "Zakup pojazdu", m_frais_reparation: "Koszty naprawy", m_cadeau: "Prezent", m_cotisation: "Składka", 
    m_abonnement: "Abonament", m_autre: "Inne", m_assurance: "Ubezpieczenie", m_impots: "Podatki",

    c_france: "Francja", c_italie: "Włochy", c_espagne: "Hiszpania", c_portugal: "Portugalia", c_russie: "Rosja",
    c_argentine: "Argentyna", c_bresil: "Brazylia", c_slovaquie: "Słowacja", c_republique_tcheque: "Czechy",
    c_pologne: "Polska", c_allemagne: "Niemcy", c_suisse: "Szwajcaria", c_roumanie: "Rumunia",
    c_ukraine: "Ukraina", c_croatie: "Chorwacja", c_slovenie: "Słowenia",
    c_royaume_uni: "Wielka Brytania", c_belgique: "Belgia", c_pays_bas: "Holandia", c_autriche: "Austria", c_suede: "Szwecja",
    c_etats_unis: "Stany Zjednoczone", c_canada: "Kanada", c_mexique: "Meksyk", c_colombie: "Kolumbia", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 9. SUÉDOIS
  // =================================================================
  "Suédois": {
    email_subject: "Kreditavi - Transferavdelningen",
    greeting: "Hej",
    // MODIFICATION ICI
    intro_message: "Direktionen för överföringsorder informerar dig om att {{debiteurNom}} framgångsrikt har registrerat en överföringsorder till din fördel. Medlen har reserverats och behandlas för närvarande i enlighet med gällande banksäkerhetsprotokoll och regulatoriska kontroller.",
    
    footer_auto: "Meddelande genererat av",
    footer_contact: "För eventuella frågor står vår kundtjänst till ditt förfogande.",
    footer_security: "Direktionen för Order",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Mottagare",
    label_execution_date: "Utförandedatum",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Bankadress",
    label_country: "Land",

    label_amount: "Reserverat belopp",
    label_sender: "Avsändare",
    label_date: "Registreringsdatum",
    label_motive: "Transaktionsreferens",
    label_bank: "Avsändande bank",
    label_key: "Nyckel",
    
    // --- STATUSES ---
    status_pending: "Väntande",
    status_processing: "Under behandling",
    status_completed: "Slutförd",
    status_rejected: "Avvisad",

    header_title: "ÖVERFÖRINGSBEVIS",
    subtitle: "Standardöverföring",
    country_dest: "Destinationsland",
    amount_sum: "Beloppet",
    currency_label: "Valuta",
    amount_digits_desc: "Belopp och valuta i siffror",
    debit_from: "Genom debitering av konto",
    debit_account_desc: "Kontonummer",
    name_desc: "Fullständigt namn / Företagsnamn",
    beneficiary: "Betalningsmottagare",
    beneficiary_label: "Till förmån för",
    beneficiary_desc: "Mottagarens namn",
    bank_info: "Bankuppgifter",
    beneficiary_sub: "(Mottagare)",
    credit_account_desc: "Konto att kreditera (IBAN)",
    bic_desc: "BIC / SWIFT-kod",
    bank_name_label: "Bank",
    bank_name_desc: "Bankens namn",
    bank_addr_label: "Bankadress",
    signature: "Signatur",

    // --- DYNAMIC VALUES ---
    m_facture: "Faktura", m_loyer: "Hyra", m_services: "Tjänster", m_achat: "Köp", m_remboursement: "Återbetalning", 
    m_salaire: "Lön", m_donation: "Donation", m_dons: "Gåvor", m_aide_familiale: "Familjestöd", m_investissement: "Investering", 
    m_voyage: "Resa", m_pret_personnel: "Personlån", m_frais_medicaux: "Sjukvårdskostnader", m_frais_etude: "Studieavgifter", 
    m_achat_vehicule: "Fordonsköp", m_frais_reparation: "Reparationskostnader", m_cadeau: "Present", m_cotisation: "Avgift", 
    m_abonnement: "Prenumeration", m_autre: "Annat", m_assurance: "Försäkring", m_impots: "Skatt",

    c_france: "Frankrike", c_italie: "Italien", c_espagne: "Spanien", c_portugal: "Portugal", c_russie: "Ryssland",
    c_argentine: "Argentina", c_bresil: "Brasilien", c_slovaquie: "Slovakien", c_republique_tcheque: "Tjeckien",
    c_pologne: "Polen", c_allemagne: "Tyskland", c_suisse: "Schweiz", c_roumanie: "Rumänien",
    c_ukraine: "Ukraina", c_croatie: "Kroatien", c_slovenie: "Slovenien",
    c_royaume_uni: "Storbritannien", c_belgique: "Belgien", c_pays_bas: "Nederländerna", c_autriche: "Österrike", c_suede: "Sverige",
    c_etats_unis: "USA", c_canada: "Kanada", c_mexique: "Mexiko", c_colombie: "Colombia", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 10. DANOIS
  // =================================================================
  "Danois": {
    email_subject: "Kreditnota - Transferafdelingen",
    greeting: "Hej",
    // MODIFICATION ICI
    intro_message: "Direktoratet for Overførselsordrer informerer dig om, at {{debiteurNom}} med succes har registreret en overførselsordre til din fordel. Midlerne er reserveret og behandles i øjeblikket i overensstemmelse med gældende banksikkerhedsprotokoller og lovgivningsmæssige kontroller.",
    
    footer_auto: "Besked genereret af",
    footer_contact: "Hvis du har spørgsmål, står vores kundeservice til din rådighed.",
    footer_security: "Direktoratet for Ordrer",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Modtager",
    label_execution_date: "Udførelsesdato",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Bankadresse",
    label_country: "Land",

    label_amount: "Reserveret beløb",
    label_sender: "Afsender",
    label_date: "Registreringsdato",
    label_motive: "Transaktionsreference",
    label_bank: "Afsenderbank",
    label_key: "Nøgle",
    
    // --- STATUSES ---
    status_pending: "Afventer",
    status_processing: "Under behandling",
    status_completed: "Udført",
    status_rejected: "Afvist",

    header_title: "OVERFØRSELSKVITTERING",
    subtitle: "Standardoverførsel",
    country_dest: "Destinationsland",
    amount_sum: "Beløbet",
    currency_label: "Valuta",
    amount_digits_desc: "Beløb og valuta i tal",
    debit_from: "Ved debitering af konto",
    debit_account_desc: "Kontonummer",
    name_desc: "Fuldt navn / Firmanavn",
    beneficiary: "Modtager",
    beneficiary_label: "Til fordel for",
    beneficiary_desc: "Modtagernavn",
    bank_info: "Bankoplysninger",
    beneficiary_sub: "(Modtager)",
    credit_account_desc: "Konto der skal krediteres (IBAN)",
    bic_desc: "BIC / SWIFT-kode",
    bank_name_label: "Bank",
    bank_name_desc: "Banknavn",
    bank_addr_label: "Bankadresse",
    signature: "Underskrift",

    // --- DYNAMIC VALUES ---
    m_facture: "Faktura", m_loyer: "Husleje", m_services: "Tjenester", m_achat: "Køb", m_remboursement: "Refusion", 
    m_salaire: "Løn", m_donation: "Donation", m_dons: "Gaver", m_aide_familiale: "Familiestøtte", m_investissement: "Investering", 
    m_voyage: "Rejse", m_pret_personnel: "Personligt lån", m_frais_medicaux: "Lægeudgifter", m_frais_etude: "Studieudgifter", 
    m_achat_vehicule: "Køb af køretøj", m_frais_reparation: "Reparationsomkostninger", m_cadeau: "Gave", m_cotisation: "Kontingent", 
    m_abonnement: "Abonnement", m_autre: "Andet", m_assurance: "Forsikring", m_impots: "Skat",

    c_france: "Frankrig", c_italie: "Italien", c_espagne: "Spanien", c_portugal: "Portugal", c_russie: "Rusland",
    c_argentine: "Argentina", c_bresil: "Brasilien", c_slovaquie: "Slovakiet", c_republique_tcheque: "Tjekkiet",
    c_pologne: "Polen", c_allemagne: "Tyskland", c_suisse: "Schweiz", c_roumanie: "Rumænien",
    c_ukraine: "Ukraine", c_croatie: "Kroatien", c_slovenie: "Slovenien",
    c_royaume_uni: "Storbritannien", c_belgique: "Belgien", c_pays_bas: "Holland", c_autriche: "Østrig", c_suede: "Sverige",
    c_etats_unis: "USA", c_canada: "Canada", c_mexique: "Mexico", c_colombie: "Colombia", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 11. NORVÉGIEN
  // =================================================================
  "Norvégien": {
    email_subject: "Kreditnota - Overføringsavdelingen",
    greeting: "Hei",
    // MODIFICATION ICI
    intro_message: "Direktoratet for overføringsordrer informerer deg om at {{debiteurNom}} har registrert en overføringsordre til din fordel. Midlene er reservert og behandles for tiden i samsvar med gjeldende banksikkerhetsprotokoller og regulatoriske kontroller.",
    
    footer_auto: "Melding generert av",
    footer_contact: "For spørsmål står vår kundeservice til din disposisjon.",
    footer_security: "Direktoratet for ordrer",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Mottaker",
    label_execution_date: "Utførelsesdato",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Bankadresse",
    label_country: "Land",

    label_amount: "Reservert beløp",
    label_sender: "Avsender",
    label_date: "Registreringsdato",
    label_motive: "Transaksjonsreferanse",
    label_bank: "Avsenderbank",
    label_key: "Nøkkel",
    
    // --- STATUSES ---
    status_pending: "Venter",
    status_processing: "Under behandling",
    status_completed: "Fullført",
    status_rejected: "Avvist",

    header_title: "OVERFØRINGSBEVIS",
    subtitle: "Standard overføring",
    country_dest: "Destinasjonsland",
    amount_sum: "Beløpet",
    currency_label: "Valuta",
    amount_digits_desc: "Beløp og valuta i tall",
    debit_from: "Ved belasting av konto",
    debit_account_desc: "Kontonummer",
    name_desc: "Fullt navn / Firmanavn",
    beneficiary: "Mottaker",
    beneficiary_label: "Til fordel for",
    beneficiary_desc: "Mottakernavn",
    bank_info: "Bankinformasjon",
    beneficiary_sub: "(Mottaker)",
    credit_account_desc: "Konto å kreditere (IBAN)",
    bic_desc: "BIC / SWIFT-kode",
    bank_name_label: "Bank",
    bank_name_desc: "Banknavn",
    bank_addr_label: "Bankadresse",
    signature: "Signatur",

    // --- DYNAMIC VALUES ---
    m_facture: "Faktura", m_loyer: "Leie", m_services: "Tjenester", m_achat: "Kjøp", m_remboursement: "Refusjon", 
    m_salaire: "Lønn", m_donation: "Donasjon", m_dons: "Gaver", m_aide_familiale: "Familiestøtte", m_investissement: "Investering", 
    m_voyage: "Reise", m_pret_personnel: "Personlig lån", m_frais_medicaux: "Medisinske utgifter", m_frais_etude: "Studieavgifter", 
    m_achat_vehicule: "Kjøp av kjøretøy", m_frais_reparation: "Reparasjonskostnader", m_cadeau: "Gave", m_cotisation: "Kontingent", 
    m_abonnement: "Abonnement", m_autre: "Annet", m_assurance: "Forsikring", m_impots: "Skatt",

    c_france: "Frankrike", c_italie: "Italia", c_espagne: "Spania", c_portugal: "Portugal", c_russie: "Russland",
    c_argentine: "Argentina", c_bresil: "Brasil", c_slovaquie: "Slovakia", c_republique_tcheque: "Tsjekkia",
    c_pologne: "Polen", c_allemagne: "Tyskland", c_suisse: "Sveits", c_roumanie: "Romania",
    c_ukraine: "Ukraina", c_croatie: "Kroatia", c_slovenie: "Slovenia",
    c_royaume_uni: "Storbritannia", c_belgique: "Belgia", c_pays_bas: "Nederland", c_autriche: "Østerrike", c_suede: "Sverige",
    c_etats_unis: "USA", c_canada: "Canada", c_mexique: "Mexico", c_colombie: "Colombia", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 12. FINLANDAIS
  // =================================================================
  "Finlandais": {
    email_subject: "Hyvitysilmoitus - Siirto-osasto",
    greeting: "Hei",
    // MODIFICATION ICI
    intro_message: "Siirtomääräysten osasto ilmoittaa, että {{debiteurNom}} on onnistuneesti rekisteröinyt hyväksesi tehdyn siirtomääräyksen. Varat on varattu ja niitä käsitellään parhaillaan voimassa olevien pankkiturvallisuusprotokollien ja säädösten mukaisten tarkastusten mukaisesti.",
    
    footer_auto: "Viestin luonut",
    footer_contact: "Asiakaspalvelumme on käytettävissänne kaikissa kysymyksissä.",
    footer_security: "Siirtomääräysten osasto",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Saaja",
    label_execution_date: "Suorituspäivä",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Pankin osoite",
    label_country: "Maa",

    label_amount: "Varattu summa",
    label_sender: "Lähettäjä",
    label_date: "Rekisteröintipäivä",
    label_motive: "Tapahtumaviite",
    label_bank: "Lähettäjäpankki",
    label_key: "Tunnus",
    
    // --- STATUSES ---
    status_pending: "Odottaa",
    status_processing: "Käsittelyssä",
    status_completed: "Valmis",
    status_rejected: "Hylätty",

    header_title: "SIIRTOTOSITE",
    subtitle: "Vakiomuotoinen siirto",
    country_dest: "Kohdemaa",
    amount_sum: "Summa",
    currency_label: "Valuutta",
    amount_digits_desc: "Summa ja valuutta numeroina",
    debit_from: "Veloitettava tili",
    debit_account_desc: "Tilinumero",
    name_desc: "Koko nimi / Yrityksen nimi",
    beneficiary: "Saaja",
    beneficiary_label: "Edunsaaja",
    beneficiary_desc: "Saajan nimi",
    bank_info: "Pankkitiedot",
    beneficiary_sub: "(Saaja)",
    credit_account_desc: "Hyvitettävä tili (IBAN)",
    bic_desc: "BIC / SWIFT-koodi",
    bank_name_label: "Pankki",
    bank_name_desc: "Pankin nimi",
    bank_addr_label: "Pankin osoite",
    signature: "Allekirjoitus",

    // --- DYNAMIC VALUES ---
    m_facture: "Lasku", m_loyer: "Vuokra", m_services: "Palvelut", m_achat: "Ostos", m_remboursement: "Hyvitys", 
    m_salaire: "Palkka", m_donation: "Lahjoitus", m_dons: "Lahjoitukset", m_aide_familiale: "Perhetuki", m_investissement: "Sijoitus", 
    m_voyage: "Matka", m_pret_personnel: "Henkilökohtainen laina", m_frais_medicaux: "Sairauskulut", m_frais_etude: "Opintomaksut", 
    m_achat_vehicule: "Ajoneuvon osto", m_frais_reparation: "Korjauskulut", m_cadeau: "Lahja", m_cotisation: "Jäsenmaksu", 
    m_abonnement: "Tilaus", m_autre: "Muu", m_assurance: "Vakuutus", m_impots: "Verot",

    c_france: "Ranska", c_italie: "Italia", c_espagne: "Espanja", c_portugal: "Portugali", c_russie: "Venäjä",
    c_argentine: "Argentiina", c_bresil: "Brasilia", c_slovaquie: "Slovakia", c_republique_tcheque: "Tšekki",
    c_pologne: "Puola", c_allemagne: "Saksa", c_suisse: "Sveitsi", c_roumanie: "Romania",
    c_ukraine: "Ukraina", c_croatie: "Kroatia", c_slovenie: "Slovenia",
    c_royaume_uni: "Yhdistynyt kuningaskunta", c_belgique: "Belgia", c_pays_bas: "Alankomaat", c_autriche: "Itävalta", c_suede: "Ruotsi",
    c_etats_unis: "Yhdysvallat", c_canada: "Kanada", c_mexique: "Meksiko", c_colombie: "Kolumbia", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 13. TCHÈQUE
  // =================================================================
  "Tchèque": {
    email_subject: "Avízo o platbě - Oddělení převodů",
    greeting: "Dobrý den",
    // MODIFICATION ICI
    intro_message: "Ředitelství převodních příkazů vás informuje, že {{debiteurNom}} úspěšně zaregistroval příkaz k převodu ve váš prospěch. Prostředky byly zajištěny a v současné době jsou zpracovávány v souladu s platnými bankovními bezpečnostními protokoly a regulačními kontrolami.",
    
    footer_auto: "Zprávu vygeneroval",
    footer_contact: "V případě dotazů je vám k dispozici náš zákaznický servis.",
    footer_security: "Ředitelství příkazů",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Příjemce",
    label_execution_date: "Datum provedení",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Adresa banky",
    label_country: "Země",

    label_amount: "Zajištěná částka",
    label_sender: "Odesílatel",
    label_date: "Datum registrace",
    label_motive: "Reference transakce",
    label_bank: "Odesílající banka",
    label_key: "Klíč",
    
    // --- STATUSES ---
    status_pending: "Čekající",
    status_processing: "Zpracovává se",
    status_completed: "Dokončeno",
    status_rejected: "Zamítnuto",

    header_title: "DOKLAD O PŘEVODU",
    subtitle: "Standardní převod",
    country_dest: "Cílová země",
    amount_sum: "Částka",
    currency_label: "Měna",
    amount_digits_desc: "Částka a měna číslicemi",
    debit_from: "Odepsáno z účtu",
    debit_account_desc: "Číslo účtu",
    name_desc: "Celé jméno / Název firmy",
    beneficiary: "Příjemce",
    beneficiary_label: "Ve prospěch",
    beneficiary_desc: "Jméno příjemce",
    bank_info: "Bankovní údaje",
    beneficiary_sub: "(Příjemce)",
    credit_account_desc: "Účet k připsání (IBAN)",
    bic_desc: "Kód BIC / SWIFT",
    bank_name_label: "Banka",
    bank_name_desc: "Název banky",
    bank_addr_label: "Adresa banky",
    signature: "Podpis",

    // --- DYNAMIC VALUES ---
    m_facture: "Faktura", m_loyer: "Nájemné", m_services: "Služby", m_achat: "Nákup", m_remboursement: "Vrácení peněz", 
    m_salaire: "Mzda", m_donation: "Dar", m_dons: "Dary", m_aide_familiale: "Rodinná podpora", m_investissement: "Investice", 
    m_voyage: "Cesta", m_pret_personnel: "Osobní půjčka", m_frais_medicaux: "Léčebné výlohy", m_frais_etude: "Školné", 
    m_achat_vehicule: "Nákup vozidla", m_frais_reparation: "Náklady na opravu", m_cadeau: "Dárek", m_cotisation: "Poplatek", 
    m_abonnement: "Předplatné", m_autre: "Jiné", m_assurance: "Pojištění", m_impots: "Daně",

    c_france: "Francie", c_italie: "Itálie", c_espagne: "Španělsko", c_portugal: "Portugalsko", c_russie: "Rusko",
    c_argentine: "Argentina", c_bresil: "Brazílie", c_slovaquie: "Slovensko", c_republique_tcheque: "Česká republika",
    c_pologne: "Polsko", c_allemagne: "Německo", c_suisse: "Švýcarsko", c_roumanie: "Rumunsko",
    c_ukraine: "Ukrajina", c_croatie: "Chorvatsko", c_slovenie: "Slovinsko",
    c_royaume_uni: "Spojené království", c_belgique: "Belgie", c_pays_bas: "Nizozemsko", c_autriche: "Rakousko", c_suede: "Švédsko",
    c_etats_unis: "USA", c_canada: "Kanada", c_mexique: "Mexiko", c_colombie: "Kolumbie", c_chili: "Chile", c_perou: "Peru"
  },

  // =================================================================
  // 14. ROUMAIN
  // =================================================================
  "Roumain": {
    email_subject: "Aviz de creditare - Direcția Transferuri",
    greeting: "Bună ziua",
    // MODIFICATION ICI
    intro_message: "Direcția Ordinelor de Transfer vă informează că {{debiteurNom}} a înregistrat cu succes un ordin de transfer în favoarea dumneavoastră. Fondurile au fost provizionate și sunt în curs de procesare conform protocoalelor de securitate bancară și verificărilor de reglementare în vigoare.",
    
    footer_auto: "Mesaj generat de",
    footer_contact: "Pentru orice întrebare, serviciul nostru clienți vă stă la dispoziție.",
    footer_security: "Direcția Ordine",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Beneficiar",
    label_execution_date: "Data execuției",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Adresa băncii",
    label_country: "Țara",

    label_amount: "Suma provizionată",
    label_sender: "Emițător",
    label_date: "Data înregistrării",
    label_motive: "Referință tranzacție",
    label_bank: "Banca emitentă",
    label_key: "Cheie",
    
    // --- STATUSES ---
    status_pending: "În așteptare",
    status_processing: "În procesare",
    status_completed: "Finalizat",
    status_rejected: "Respins",

    header_title: "ORDIN DE TRANSFER",
    subtitle: "Transfer standard",
    country_dest: "Țara de destinație",
    amount_sum: "Suma de",
    currency_label: "Monedă",
    amount_digits_desc: "Suma și moneda în cifre",
    debit_from: "Prin debitarea contului",
    debit_account_desc: "Număr cont",
    name_desc: "Nume complet / Nume companie",
    beneficiary: "Beneficiar",
    beneficiary_label: "În beneficiul",
    beneficiary_desc: "Numele beneficiarului",
    bank_info: "Date bancare",
    beneficiary_sub: "(Beneficiar)",
    credit_account_desc: "Cont de creditat (IBAN)",
    bic_desc: "Cod BIC / SWIFT",
    bank_name_label: "Bancă",
    bank_name_desc: "Numele băncii",
    bank_addr_label: "Adresa băncii",
    signature: "Semnătură",

    // --- DYNAMIC VALUES ---
    m_facture: "Factură", m_loyer: "Chirie", m_services: "Servicii", m_achat: "Cumpărătură", m_remboursement: "Rambursare", 
    m_salaire: "Salariu", m_donation: "Donație", m_dons: "Donații", m_aide_familiale: "Ajutor familial", m_investissement: "Investiție", 
    m_voyage: "Călătorie", m_pret_personnel: "Împrumut personal", m_frais_medicaux: "Cheltuieli medicale", m_frais_etude: "Taxe de studiu", 
    m_achat_vehicule: "Achiziție vehicul", m_frais_reparation: "Costuri reparații", m_cadeau: "Cadou", m_cotisation: "Cotizație", 
    m_abonnement: "Abonament", m_autre: "Altele", m_assurance: "Asigurare", m_impots: "Impozite",

    c_france: "Franța", c_italie: "Italia", c_espagne: "Spania", c_portugal: "Portugalia", c_russie: "Rusia",
    c_argentine: "Argentina", c_bresil: "Brazilia", c_slovaquie: "Slovacia", c_republique_tcheque: "Republica Cehă",
    c_pologne: "Polonia", c_allemagne: "Germania", c_suisse: "Elveția", c_roumanie: "România",
    c_ukraine: "Ucraina", c_croatie: "Croația", c_slovenie: "Slovenia",
    c_royaume_uni: "Regatul Unit", c_belgique: "Belgia", c_pays_bas: "Țările de Jos", c_autriche: "Austria", c_suede: "Suedia",
    c_etats_unis: "SUA", c_canada: "Canada", c_mexic: "Mexic", c_columbia: "Columbia", c_chili: "Chile", c_peru: "Peru"
  },

  // =================================================================
  // 15. GREC
  // =================================================================
  "Grec": {
    email_subject: "Ειδοποίηση πίστωσης - Τμήμα Μεταφορών",
    greeting: "Γεια σας",
    // MODIFICATION ICI
    intro_message: "Η Διεύθυνση Εντολών Μεταφοράς σας ενημερώνει ότι ο/η {{debiteurNom}} καταχώρησε επιτυχώς μια εντολή μεταφοράς υπέρ σας. Τα κεφάλαια έχουν δεσμευτεί και επεξεργάζονται επί του παρόντος σύμφωνα με τα πρωτόκολλα τραπεζικής ασφάλειας και τους κανονιστικούς ελέγχους.",
    
    footer_auto: "Μήνυμα από",
    footer_contact: "Για τυχόν απορίες, η εξυπηρέτηση πελατών μας είναι στη διάθεσή σας.",
    footer_security: "Διεύθυνση Εντολών",
    
    // --- NEW LABELS ---
    label_beneficiary_name: "Δικαιούχος",
    label_execution_date: "Ημερομηνία εκτέλεσης",
    label_iban: "IBAN",
    label_bic: "BIC/SWIFT",
    label_bank_address: "Διεύθυνση τράπεζας",
    label_country: "Χώρα",

    label_amount: "Δεσμευμένο ποσό",
    label_sender: "Εκδότης",
    label_date: "Ημερομηνία εγγραφής",
    label_motive: "Αναφορά συναλλαγής",
    label_bank: "Εκδότρια Τράπεζα",
    label_key: "Κλειδί",
    
    // --- STATUSES ---
    status_pending: "Σε αναμονή",
    status_processing: "Σε επεξεργασία",
    status_completed: "Ολοκληρώθηκε",
    status_rejected: "Απορρίφθηκε",

    header_title: "ΑΠΟΔΕΙΚΤΙΚΟ ΜΕΤΑΦΟΡΑΣ",
    subtitle: "Τυπική μεταφορά",
    country_dest: "Χώρα προορισμού",
    amount_sum: "Το ποσό των",
    currency_label: "Νόμισμα",
    amount_digits_desc: "Ποσό και νόμισμα αριθμητικά",
    debit_from: "Με χρέωση λογαριασμού",
    debit_account_desc: "Αριθμός λογαριασμού",
    name_desc: "Ονοματεπώνυμο / Επωνυμία",
    beneficiary: "Δικαιούχος",
    beneficiary_label: "Προς όφελος του",
    beneficiary_desc: "Όνομα δικαιούχου",
    bank_info: "Τραπεζικά στοιχεία",
    beneficiary_sub: "(Δικαιούχος)",
    credit_account_desc: "Λογαριασμός πίστωσης (IBAN)",
    bic_desc: "Κωδικός BIC / SWIFT",
    bank_name_label: "Τράπεζα",
    bank_name_desc: "Όνομα τράπεζας",
    bank_addr_label: "Διεύθυνση τράπεζας",
    signature: "Υπογραφή",

    // --- DYNAMIC VALUES ---
    m_facture: "Τιμολόγιο", m_loyer: "Ενοίκιο", m_services: "Υπηρεσίες", m_achat: "Αγορά", m_remboursement: "Επιστροφή χρημάτων", 
    m_salaire: "Μισθός", m_donation: "Δωρεά", m_dons: "Δωρεές", m_aide_familiale: "Οικογενειακή βοήθεια", m_investissement: "Επένδυση", 
    m_voyage: "Ταξίδι", m_pret_personnel: "Προσωπικό δάνειο", m_frais_medicaux: "Ιατρικά έξοδα", m_frais_etude: "Δίδακτρα", 
    m_achat_vehicule: "Αγορά οχήματος", m_frais_reparation: "Έξοδα επισκευής", m_cadeau: "Δώρο", m_cotisation: "Συνδρομή", 
    m_abonnement: "Συνδρομή", m_autre: "Άλλο", m_assurance: "Ασφάλιση", m_impots: "Φόροι",

    c_france: "Γαλλία", c_italie: "Ιταλία", c_espagne: "Ισπανία", c_portugal: "Πορτογαλία", c_russie: "Ρωσία",
    c_argentine: "Αργεντινή", c_bresil: "Βραζιλία", c_slovaquie: "Σλοβακία", c_republique_tcheque: "Τσεχία",
    c_pologne: "Πολωνία", c_allemagne: "Γερμανία", c_suisse: "Ελβετία", c_roumanie: "Ρουμανία",
    c_ukraine: "Ουκρανία", c_croatie: "Κροατία", c_slovenie: "Σλοβενία",
    c_royaume_uni: "Ηνωμένο Βασίλειο", c_belgique: "Βέλγιο", c_pays_bas: "Κάτω Χώρες", c_autriche: "Αυστρία", c_suede: "Σουηδία",
    c_etats_unis: "ΗΠΑ", c_canada: "Καναδάς", c_mexique: "Μεξικό", c_colombie: "Κολομβία", c_chili: "Χιλή", c_perou: "Περού"
  }
};